#Naive Bayes Classification

##Uploading file
The file that is uploaded is used_cars_proccessed.csv. It's used cars data but has been going through preprocessing steps so it's ready to use.

In [1]:
from google.colab import files
datafile = files.upload()

##Convert data into dataframe

In [2]:
import pandas as pd

df_nb = pd.read_csv('used_cars_processed.csv',engine="python")
pd.set_option('display.max_columns', None)

df_nb= df_nb.loc[:, df_nb.columns != 'Unnamed: 0'] #dropping index column
df_nb

,region,price,year,manufacturer,model,fuel,title_status,transmission,drive,type,state
0,12,17899.0,2012.0,37,1891,2,0,1,0,4,0
1,12,8795.0,2016.0,11,1525,2,0,0,0,9,0
2,12,8795.0,2016.0,11,1525,2,0,0,0,9,0
3,12,13999.0,2009.0,31,1525,2,0,0,0,8,0
4,12,14500.0,2007.0,12,2876,2,0,0,0,8,0
...,...,...,...,...,...,...,...,...,...,...,...
18129,5,2200.0,2005.0,28,2340,2,0,0,0,0,3
18130,5,24999.0,2017.0,34,3512,2,0,1,0,9,3
18131,5,12127.0,2018.0,28,2836,2,0,0,1,9,3
18132,5,8795.0,2019.0,18,1917,2,0,0,0,0,3
18133,5,14661.0,2017.0,36,1079,2,0,0,1,9,3

##Making 'price' feature into categorical
Price divided by two categories: <= mean and < mean

If below and equals to mean: 0
If above mean: 1

In [6]:
mean_price = df_nb.price.mean()

df_nb.loc[df_nb.price <= mean_price, 'price'] = 0
df_nb.loc[df_nb.price > mean_price, 'price'] = 1

# df_nb

Counter({0.0: 11284, 1.0: 6850})

##Splitting data into training and testing datasets

In [9]:
from sklearn.model_selection import train_test_split

df_nb2 = df_nb.copy()
y_nb = df_nb2.pop('price').values
df_nb_train, df_nb_test = train_test_split(df_nb, train_size= 0.7,test_size= 0.3)
y_nb_train = df_nb_train.pop('price').values
y_nb_test = df_nb_test.pop('price').values
df_nb_train, df_nb_test, y_nb_train, y_nb_test

(       region    year  manufacturer  model  fuel  title_status  transmission  \
 13108      10  2016.0            11   1298     2             0             0
 13037      10  2004.0            11   1551     0             0             0
 1285       15  2009.0            11   1418     2             0             0
 14827      16  2004.0            31     14     2             0             0
 10203       9  2013.0            14   2403     2             0             0
 ...       ...     ...           ...    ...   ...           ...           ...
 7093        6  2016.0            18    949     2             0             0
 5505        3  2016.0             6   1157     2             0             0
 2017       15  2000.0            34   1999     2             0             1
 767        15  2004.0            18   1908     2             0             0
 11124      10  2014.0             7    865     2             0             0

        drive  type  state
 13108      0     9      1
 13037      0     9      1
 1285       0     9      2
 14827      0     7      1
 10203      1    11      1
 ...      ...   ...    ...
 7093       1     0      1
 5505       0     9      1
 2017       0     4      2
 767        0     0      2
 11124      2     3      1

 [12693 rows x 10 columns],
        region    year  manufacturer  model  fuel  title_status  transmission  \
 5955        3  2008.0             6   3103     2             0             0
 5606        3  2007.0            11    435     2             0             0
 1885       15  2010.0            11   3210     2             0             0
 11042      10  2010.0            12   2906     2             0             0
 18048       5  2014.0            28   3265     2             0             0
 ...       ...     ...           ...    ...   ...           ...           ...
 5005        3  2007.0            31    249     0             0             1
 130        14  2007.0            15   3438     2             0             0
 15769       0  2012.0            11   1527     2             0             0
 3558        1  2017.0             5   1369     2             0             0
 10075       9  1999.0            12   3122     2             0             0

        drive  type  state
 5955       0     7      1
 5606       0     0      1
 1885       0     9      2
 11042      0     9      1
 18048      0    10      3
 ...      ...   ...    ...
 5005       0     9      1
 130        0     0      0
 15769      0     9      3
 3558       0     7      1
 10075      0     0      1

 [5441 rows x 10 columns],
 array([0., 1., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 1., 1., 0.]))

##Model: Using GaussianNB

In [0]:
from sklearn.naive_bayes import GaussianNB
from imblearn.combine import SMOTEENN

nb_model = GaussianNB()
smote_enn = SMOTEENN(random_state=100)
df_nb_train, y_nb_train = smote_enn.fit_resample(df_nb_train, y_nb_train)
nb_model.fit(df_nb_train, y_nb_train)
y_nb_pred = nb_model.predict(df_nb_test)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

##Result of Prediction

In [0]:
res = df_nb_test.copy()
res['actual class'] = y_nb_test
res['predicted class'] = y_nb_pred
res

,region,year,manufacturer,model,fuel,title_status,transmission,drive,type,state,actual class,predicted class
15532,0,2015.0,31,52,2,0,0,0,10,3,1.0,1.0
10771,10,2004.0,14,974,2,0,0,1,9,1,0.0,0.0
16334,0,2011.0,24,818,2,0,0,2,9,3,1.0,1.0
11265,10,2003.0,19,2420,2,0,0,0,9,1,0.0,0.0
8501,9,2008.0,18,3471,2,0,0,0,0,1,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1125,15,2008.0,11,3148,2,0,0,0,9,2,0.0,0.0
4540,3,2016.0,7,856,2,0,0,0,3,1,1.0,1.0
915,15,2014.0,38,3554,2,0,0,0,0,2,1.0,1.0
16614,0,2014.0,11,1525,2,0,0,0,8,3,1.0,1.0
11731,10,2010.0,23,2266,2,0,1,0,4,1,0.0,1.0

##Evaluation: Accuracy -- Cross Validation

In [0]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(nb_model, df_nb2, y_nb, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.68 (+/- 0.12)

# KNN Classification

## Converting data into dataframe

In [0]:
import pandas as pd

df_knn = pd.read_csv('used_cars_processed.csv',engine="python")
pd.set_option('display.max_columns', None)

df_knn= df_knn.loc[:, df_knn.columns != 'Unnamed: 0'] #dropping index column
# df_knn

##Making 'price' feature into categorical
Price divided by two categories: <= mean and < mean

If below and equals to mean: 0
If above mean: 1

In [0]:
mean_price = df_knn.price.mean()

df_knn.loc[df_knn.price <= mean_price, 'price'] = 0
df_knn.loc[df_knn.price > mean_price, 'price'] = 1
df_knn

,region,price,year,manufacturer,model,fuel,title_status,transmission,drive,type,state
0,12,1.0,2012.0,37,1891,2,0,1,0,4,0
1,12,0.0,2016.0,11,1525,2,0,0,0,9,0
2,12,0.0,2016.0,11,1525,2,0,0,0,9,0
3,12,1.0,2009.0,31,1525,2,0,0,0,8,0
4,12,1.0,2007.0,12,2876,2,0,0,0,8,0
...,...,...,...,...,...,...,...,...,...,...,...
18129,5,0.0,2005.0,28,2340,2,0,0,0,0,3
18130,5,1.0,2017.0,34,3512,2,0,1,0,9,3
18131,5,1.0,2018.0,28,2836,2,0,0,1,9,3
18132,5,0.0,2019.0,18,1917,2,0,0,0,0,3
18133,5,1.0,2017.0,36,1079,2,0,0,1,9,3

##Splitting data into training and testing datasets

In [0]:
from sklearn.model_selection import train_test_split
df_knn2 = df_knn.copy()
y_knn = df_knn2.pop('price').values
df_knn_train, df_knn_test = train_test_split(df_knn, train_size= 0.7,test_size= 0.3)
y_knn_train = df_knn_train.pop('price').values
y_knn_test = df_knn_test.pop('price').values

df_knn_train, df_knn_test, y_knn_train, y_knn_test

(       region    year  manufacturer  model  fuel  title_status  transmission  \
 11351      10  2002.0            36   2850     2             0             0
 12750      10  2014.0            28    277     2             0             2
 17716       0  2013.0            31     66     2             0             0
 9121        9  2010.0            11   1625     2             0             0
 2667       15  2018.0             9   1899     2             0             0
 ...       ...     ...           ...    ...   ...           ...           ...
 11465      10  2016.0            11   1317     2             0             0
 16629       0  2016.0            37   1269     1             0             0
 1773       15  2011.0            34   2003     2             0             0
 2650       15  2013.0             7   2936     2             4             0
 6404        4  2007.0            15   1335     2             0             0

        drive  type  state
 11351      0     0      1
 12750      2     3      1
 17716      0    10      3
 9121       0    10      1
 2667       1    11      2
 ...      ...   ...    ...
 11465      0     0      1
 16629      1     4      3
 1773       0     9      2
 2650       0     9      2
 6404       0     9      1

 [12693 rows x 10 columns],
        region    year  manufacturer  model  fuel  title_status  transmission  \
 5366        3  2004.0            11   1483     4             0             0
 7431        8  2015.0            24   2746     2             0             0
 13037      10  2004.0            11   1551     0             0             0
 776        15  2007.0            11   2026     0             0             0
 14282      11  2019.0            28   3441     2             0             0
 ...       ...     ...           ...    ...   ...           ...           ...
 13348      11  2007.0            12   1375     2             0             0
 10665      10  2012.0             9   1245     2             0             0
 1242       15  2016.0            11   1545     2             0             0
 10274       9  2011.0             9    935     2             0             0
 826        15  2013.0            37   2077     0             0             0

        drive  type  state
 5366       0     0      1
 7431       0     9      1
 13037      0     9      1
 776        0     1      2
 14282      0     9      1
 ...      ...   ...    ...
 13348      1     0      1
 10665      2     0      1
 1242       0     9      2
 10274      2     9      1
 826        1    12      2

 [5441 rows x 10 columns],
 array([0., 1., 1., ..., 0., 1., 0.]),
 array([0., 0., 1., ..., 1., 1., 0.]))

##Model: Using KNeighborsClassifier

In [0]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=2)
knn_model.fit(df_knn_train, y_knn_train)
y_knn_pred = knn_model.predict(df_knn_test)

##Result of Prediction

In [0]:
res = df_knn_test.copy()
res['actual class'] = y_knn_test
res['predicted class'] = y_knn_pred
res

,region,year,manufacturer,model,fuel,title_status,transmission,drive,type,state,actual class,predicted class
5366,3,2004.0,11,1483,4,0,0,0,0,1,0.0,0.0
7431,8,2015.0,24,2746,2,0,0,0,9,1,0.0,0.0
13037,10,2004.0,11,1551,0,0,0,0,9,1,1.0,0.0
776,15,2007.0,11,2026,0,0,0,0,1,2,0.0,0.0
14282,11,2019.0,28,3441,2,0,0,0,9,1,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
13348,11,2007.0,12,1375,2,0,0,1,0,1,0.0,0.0
10665,10,2012.0,9,1245,2,0,0,2,0,1,0.0,0.0
1242,15,2016.0,11,1545,2,0,0,0,9,2,1.0,1.0
10274,9,2011.0,9,935,2,0,0,2,9,1,1.0,0.0
826,15,2013.0,37,2077,0,0,0,1,12,2,0.0,0.0

##Evaluation: using cross validation and accuracy to make it more precise

In [0]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(knn_model, df_knn2, y_knn, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.80 (+/- 0.10)